Update maxiwall
updated new code without caffeine

diff --git a/maxiwall b/maxiwall
--- a/maxiwall
+++ b/maxiwall
@@ -1,7 +1,7 @@
 #!/bin/bash
 # ==================================================
 _APP_SPECIFIC_NAME="Maxiwall"
-_APP_VERSION="0.2"
+_APP_VERSION="0.3"
 _APP_STATUS="beta"
 _APP_INFO="${_APP_SPECIFIC_NAME} (maxiwall) is bash script to manage CSF, AbuseIPDB and Suricata
 with extra features. This script is also a wrapper to manage suricata .lua report with IPS capability"
@@ -11,6 +11,7 @@ _AUTHOR="Author: Arafat Ali | Email: arafat@sofibox.com | (C) 2019-2021"
 
 # This script works best with suricata + maxiwall.lua at code/lua-output/maxiwall.lua
 
+# Watch the log file
 usage() {
   local usage_file
   usage_file="${SCRIPT_PATH}/readme.txt"
@@ -21,6 +22,21 @@ usage() {
     echo "[${SCRIPT_NAME}]: Error, the usage file ${usage_file} does not exist."
     exit 1
   fi
+}
+
+# This function will display a confirmation to continue (force continue; no exit function)
+_confirm() {
+  # call with a prompt string or use a default
+  read -r -p "[${SCRIPT_NAME}]: ${1:-Continue? [y] Exit? [CTRL+C]} " response
+  case "$response" in
+  [yY][eE][sS] | [yY])
+    return 0
+    ;;
+  *)
+    echo "[${SCRIPT_NAME}]: Invalid response to the question!"
+    _confirm "$1"
+    ;;
+  esac
 }
 
 check_status() {
@@ -196,12 +212,60 @@ clear_database_cache() {
   echo "[${SCRIPT_NAME}]: Clearing BLCHECK cache file ..."
   cat /dev/null >"${BLCHECK_CACHED_IP_FILE}"
   check_status "$?"
-  echo "[${SCRIPT_NAME}]: Clearing maxiwall suspicious IP and cache files and ..."
+  echo "[${SCRIPT_NAME}]: Clearing maxiwall suspicious log IP and cache files ..."
   cat /dev/null >"${MAXIWALL_SUSPICIOUS_IP_LOG_CACHE}"
   rm -rf "${CACHE_PATH}/ips"
   check_status "$?"
 
 }
+
+update_scripts() {
+  echo "[${SCRIPT_NAME}]: Copying suricata.yaml into ${SURICATA_CONF} ..."
+  cp "${CODE_PATH}/etc/suricata/suricata.yaml" "${SURICATA_CONF}"
+  check_status "$?"
+  echo ""
+
+  echo "[${SCRIPT_NAME}]: Copying suricata-test.yaml into ${SURICATA_TEST_CONF} ..."
+  cp "${CODE_PATH}/etc/suricata/suricata-test.yaml" "${SURICATA_TEST_CONF}"
+  check_status "$?"
+  echo ""
+  echo "[${SCRIPT_NAME}]: Copying maxiwall.lua into ${MAXIWALL_LUA} ..."
+  cp "${CODE_PATH}/etc/suricata/lua-output/maxiwall.lua" "${MAXIWALL_LUA}"
+  check_status "$?"
+  echo ""
+  echo "[${SCRIPT_NAME}]: Copying maxiwall-http.lua into ${MAXIWALL_HTTP_LUA} ..."
+  cp "${CODE_PATH}/etc/suricata/lua-output/maxiwall-http.lua" "${MAXIWALL_HTTP_LUA}"
+  check_status "$?"
+  echo ""
+  echo "[${SCRIPT_NAME}]: Copying maxiwall.rules into ${MAXIWALL_RULES} ..."
+  cp "${CODE_PATH}/etc/suricata/rules/maxiwall.rules" "${MAXIWALL_RULES}"
+  check_status "$?"
+  echo ""
+  echo "[${SCRIPT_NAME}]: Copying maxiwall-test.rules into ${MAXIWALL_TEST_RULES} ..."
+  cp "${CODE_PATH}/etc/suricata/rules/maxiwall-test.rules" "${MAXIWALL_TEST_RULES}"
+  check_status "$?"
+  echo ""
+  echo "[${SCRIPT_NAME}]: Copying enable.conf into ${SURICATA_ENABLE_CONF} ..."
+  cp "${CODE_PATH}/etc/suricata/enable.conf" "${SURICATA_ENABLE_CONF}"
+  check_status "$?"
+  echo ""
+  echo "[${SCRIPT_NAME}]: Copying disable.conf into ${SURICATA_DISABLE_CONF} ..."
+  cp "${CODE_PATH}/etc/suricata/disable.conf" "${SURICATA_DISABLE_CONF}"
+  check_status "$?"
+  echo ""
+  echo "[${SCRIPT_NAME}]: Copying drop.conf into ${SURICATA_DROP_CONF} ..."
+  cp "${CODE_PATH}/etc/suricata/disable.conf" "${SURICATA_DROP_CONF}"
+  check_status "$?"
+  echo ""
+  echo "[${SCRIPT_NAME}]: Copying suricata.service into ${SURICATA_SERVICE} ..."
+  cp "${CODE_PATH}/etc/systemd/system/suricata.service" "${SURICATA_SERVICE}"
+  check_status "$?"
+  echo ""
+  echo "[${SCRIPT_NAME}]: Reloading systemd daemon service ..."
+  systemctl daemon-reload
+  check_status "$?"
+}
+
 # This works with IPv4 and IPv6 with any valid form of CIDR subnet
 # ip_to_cidr 1.1.1.1 24
 ip_to_cidr() {
@@ -891,6 +955,89 @@ aipdb_report_ip_info() {
     exit 1
 
   fi
+
+}
+# maxiwall linode-block-ip <ip> --firewall-label <firewall_label_name>
+# maxiwall linode-block-ip <ip> --firewall-label <firewall_label_name>
+# eg: maxiwall linode-block-ip 1.1.1.1 --firewall-label maxiwall1
+# eg: maxiwall linode-block-ip 1.1.1.1 --firewall-label maxiwall1
+linode_block_ip() {
+  local target ip retval
+  shift
+
+  target="$1"
+
+  [[ "${VERBOSE}" == "true" ]] && echo "All args: $*"
+  if ipcalc -4 -sc "${target}"; then
+    [[ "${VERBOSE}" == "true" ]] && echo "[${SCRIPT_NAME}]: Target is valid IPv4"
+    ip="${target}"
+  elif ipcalc -6 -sc "${target}"; then
+    [[ "${VERBOSE}" == "true" ]] && echo "[${SCRIPT_NAME}]: Target is valid IPv6"
+    ip=$(ipcalc -s "${target}" | awk '/Full Address:/{ print $NF }')
+  else
+    [[ "${VERBOSE}" == "true" ]] && echo "[${SCRIPT_NAME}]: Target is not IPv4 nor IPv6 (treating as DNS)"
+    ip=$(dig +short -t "a" +time=3 +tries=2 "${target}" | grep -om 1 "${REGEX_IPV4}")
+    if [ -z "${ip}" ]; then
+      ip=$(dig +short -t "aaaa" +time=3 +tries=2 "${target}" | grep -om 1 "${REGEX_IPV6}")
+      ip=$(ipcalc -s "${ip}" | awk '/Full Address:/{ print $NF }')
+    fi
+  fi
+
+  # Sometimes target is not reachable or contains another domain (unresolvable), in this case we quit
+  if [ -z "${ip}" ]; then
+    [[ "${VERBOSE}" == "true" ]] && echo "[${SCRIPT_NAME}]: Error, No DNS record found for target ${target}"
+    echo "error-no-dns-record"
+    exit 1
+  fi
+
+  [[ "${VERBOSE}" == "true" ]] && echo "[${SCRIPT_NAME}]: Using target ${target}, resolved to IP ${ip}"
+
+  [[ "${VERBOSE}" == "true" ]] && echo "[${SCRIPT_NAME}]: Looking for linode firewall with labels ${FIREWALL_LABEL} ..."
+  linode_id=$(linode-cli --pretty --json --suppress-warnings linodes list --label "${BOX_HOSTNAME_FQHN}" | jq -cr '.[].id')
+  firewall_id=$(linode-cli --pretty --json --suppress-warnings firewalls list --label "${FIREWALL_LABEL}" | jq -cr '.[].id')
+  if [ -n "${firewall_id}" ]; then
+    echo "Main firewall ${FIREWALL_LABEL} found with ID: ${firewall_id}"
+  else
+    echo "Main firewall ${FIREWALL_LABEL} not found. Creating empty firewall ${FIREWALL_LABEL} in linode ..."
+    if [ -z "${FIREWALL_LABEL}" ]; then
+      echo "The FIREWALL_LABEL is empty!"
+      exit 1
+    else
+      echo "FIREWALL_LABEL ${FIREWALL_LABEL}"
+    fi
+    # linode-cli firewalls create \
+    #   --label "${FIREWALL_LABEL}" \
+    #   --rules.outbound_policy ACCEPT \
+    #   --rules.inbound_policy ACCEPT
+
+    # TODO this is a bit complicated
+    # ports=all
+
+    #  [ip: 1.1.1.1 [action: drop [label: "block" [description: "not sure"
+
+    #   ipv4=("1.1.1.1" "1.2.3.4" "4.4.4.4")
+    #   protocol1="{\"ports\":\"1-65535\",\"protocol\":\"TCP\",\"addresses\":{\"ipv4\":[\"0.0.0.0/0\"]},\"action\":\"DROP\",\"label\":\"Drop-TCP-Inbound\",\"description\":\"Drop-TCP-Inbound-IPs\"}"
+
+    # INBOUND_RULES='[{"ports":"All","protocol":"TCP","addresses":{"ipv4":["0.0.0.0/0"]},"action":"DROP","label":"accept-inbound-SSH","description":"allow inbound ssh to instances"},{"ports":"6443","protocol":"TCP","addresses":{"ipv4":["0.0.0.0/0"]},"action":"ACCEPT","label":"control-ingress","description":"allows ingress to k8s control plane"},{"ports":"1-65535","protocol":"TCP","addresses":{"ipv4":["192.168.0.0/16"]},"action":"ACCEPT","label":"inter-controller-tcp","description":"allow communication between controllers over tcp"},{"ports":"1-65535","protocol":"UDP","addresses":{"ipv4":["192.168.0.0/16"]},"action":"ACCEPT","label":"inter-controller-udp","description":"allow inter-controller communication over udp"},{"ports":"1-65535","protocol":"TCP","addresses":{"ipv4":["10.200.0.0/16"]},"action":"ACCEPT","label":"k8s-pods-traffic","description":"allow communication between pods via tcp"},{"ports":"1-65535","protocol":"UDP","addresses":{"ipv4":["10.200.0.0/16"]},"action":"ACCEPT","label":"k8s-pods-traffic","description":"allow communication between pods via udp"},{"protocol":"ICMP","addresses":{"ipv4":["0.0.0.0/0"]},"action":"ACCEPT","label":"icmp-ingress","description":"allow pings to hit us"}]'
+
+    firewall_id=$(linode-cli --pretty --json --suppress-warnings firewalls list --label "${FIREWALL_LABEL}" | jq -cr '.[].id')
+
+    firewall_id=$(linode-cli firewalls create \
+      --label "${FIREWALL_LABEL}" \
+      --rules.outbound_policy ACCEPT \
+      --rules.inbound_policy ACCEPT \
+      --rules.inbound "${INBOUND_RULES}" \
+      --json |
+      jq -r '.[].id')
+
+    linode-cli firewalls device-create "${firewall_id}" \
+      --id "${linode_id}" \
+      --type "linode"
+  fi
+
+  # linode-cli firewalls rules-update "${firewall_id}" \
+  # --inbound '[{"protocol": "TCP", "ports": "22, 80, 8080, 443", "addresses": {"ipv4": ["192.0.2.1", "192.0.2.0/24"]}, "action": "DROP"}]' \
+  # --outbound '[{"protocol": "TCP", "ports": "49152-65535", "addresses": {"ipv4": ["192.0.2.1", "192.0.2.0/24"]}, "action": "DROP"}]'
 
 }
 
@@ -1738,6 +1885,10 @@ BLCHECK_CACHED_IP_FILE="$(blcheck get-default-output-file)"
 BLCHECK_SERVICE_FILE="${CONFIG_PATH}/blcheck_service_file.lst"
 
 SURICATA_CONF="/etc/suricata/suricata.yaml"
+SURICATA_TEST_CONF="/etc/suricata/suricata-test.yaml"
+SURICATA_ENABLE_CONF="/etc/suricata/enable.conf"
+SURICATA_DISABLE_CONF="/etc/suricata/disable.conf"
+SURICATA_DROP_CONF="/etc/suricata/drop.conf"
 SURICATA_LOG="/var/log/suricata/suricata.log"
 SURICATA_FAST_LOG="/var/log/suricata/fast.log"
 SURICATA_HTTP_LOG="/var/log/suricata/http.log"
@@ -1752,6 +1903,12 @@ MAXIWALL_SUPPRESSED_MSG_FILE="${CONFIG_PATH}/maxiwall_sup_msg.lst"
 MAXIWALL_LOG="/var/log/suricata/maxiwall.log"
 MAXIWALL_ALERT_LOG="/var/log/suricata/${MAXIWALL_ALERT_LOG_NAME}"
 MAXIWALL_LUA="/etc/suricata/lua-output/maxiwall.lua"
+MAXIWALL_HTTP_LUA="/etc/suricata/lua-output/maxiwall-http.lua"
+mkdir -p /etc/suricata/lua-output
+MAXIWALL_RULES="/etc/suricata/rules/maxiwall.rules"
+MAXIWALL_TEST_RULES="/etc/suricata/rules/maxiwall-test.rules"
+mkdir -p /etc/suricata/rules
+SURICATA_SERVICE="/lib/systemd/system/suricata.service"
 MAXIWALL_ALERT_LOG_LIST="${CONFIG_PATH}/maxiwall_alert_log.lst"
 MAXIWALL_SUSPICIOUS_IP_LOG_CACHE="${CACHE_PATH}/maxiwall_suspicious_ip_log.cache"
 touch "${MAXIWALL_SUSPICIOUS_IP_LOG_CACHE}"
@@ -1778,6 +1935,16 @@ while [ "$#" -gt 0 ]; do
     exit 0
     break
     ;;
+  edit-test-rule)
+    nano -c "${MAXIWALL_TEST_RULES}"
+    exit 0
+    break
+    ;;
+  edit-rule | editrule)
+    nano -c "${MAXIWALL_RULES}"
+    exit 0
+    break
+    ;;
   test-mode | test-rule)
     # This will test rule
     # To generate rule test, we can use telnet to this server
@@ -1791,20 +1958,62 @@ while [ "$#" -gt 0 ]; do
     exit 0
     break
     ;;
+  update-scripts | update-script | update-codes | update-code)
+    update_scripts
+    echo ""
+    exit 0
+    break
+    ;;
   init)
     # TODO add testing APIDBCHECK URL AIPDB_REPORT_URL for 200 status
     echo "[${SCRIPT_NAME}]: Stopping suricata.service ..."
     systemctl stop suricata
+    # Update script here
+    echo ""
+    update_scripts
+    echo ""
     echo "[${SCRIPT_NAME}]: Clear all suricata log files ..."
     rm -rf /var/log/suricata/*
+    echo ""
     clear_database_cache
     # TODO only enable below when in production because this is so slow
+    echo ""
     echo -n "[${SCRIPT_NAME}]: Updating suricata rule sources ..."
     suricata-update update-sources
+    echo ""
     echo -n "[${SCRIPT_NAME}]: Updating suricata rule definition ..."
     suricata-update 2>&1 | grep -v 'Found duplicate rule SID'
+    echo ""
     echo "[${SCRIPT_NAME}]: Starting suricata.service ..."
     systemctl start suricata
+    exit 0
+    break
+    ;;
+  clear-csf | csf-clear | clear-csf-ip)
+    echo "[${SCRIPT_NAME}]: Copying csf.deny_empty into ${CSF_IP_PERMANENT_BLOCK_FILE} ..."
+    _confirm "Warning, this will clear all csf.deny including the '#do not delete' entries!"
+    cp "${CODE_PATH}/etc/csf/csf.deny_empty" "${CSF_IP_PERMANENT_BLOCK_FILE}"
+    check_status "$?"
+    echo "[${SCRIPT_NAME}]: Flushing csf.deny ..."
+    csf -df >/dev/null
+    check_status "$?"
+    echo "[${SCRIPT_NAME}]: Restarting CSF and LFD ..."
+    csf -ra >/dev/null
+    check_status "$?"
+    echo ""
+    exit 0
+    break
+    ;;
+  add-extra-rules)
+    echo "Enabling suricata 3rd party rules ..."
+    suricata-update enable-source sslbl/ssl-fp-blacklist
+    suricata-update enable-source ptresearch/attackdetection
+    suricata-update enable-source etnetera/aggressive
+    suricata-update enable-source oisf/trafficid
+    suricata-update enable-source sslbl/ja3-fingerprints
+    suricata-update enable-source et/open
+    suricata-update add-source timon-rules/cybergon https://gitlab.com/cybergon/timon-rules/raw/master/cybergon.rules
+    echo ""
     exit 0
     break
     ;;
@@ -1841,6 +2050,12 @@ while [ "$#" -gt 0 ]; do
       esac
     done
     scan_log "$@"
+    exit 0
+    break
+    ;;
+  # This is linode firewall
+  lf | linode-firewall)
+
     exit 0
     break
     ;;
@@ -1886,6 +2101,7 @@ while [ "$#" -gt 0 ]; do
   update-rule | suricata-update)
     echo -n "[${SCRIPT_NAME}]: Updating suricata rule definition ..."
     suricata-update update-sources
+    check_status "$?"
     suricata-update 2>&1 | grep -v 'Found duplicate rule SID'
     check_status "$?"
     exit 0
@@ -1896,9 +2112,9 @@ while [ "$#" -gt 0 ]; do
     if [ "${EDIT_FILE}" == "suricata.log" ]; then
       nano -c "${SURICATA_LOG}"
     elif [[ "${EDIT_FILE}" == "suricata.conf" || "${EDIT_FILE}" == "suricata.yaml" ]]; then
-      nano -c "${SURICATA_CONF}"
+      nano -c "${CODE_PATH}/${SURICATA_CONF}"
     elif [ "${EDIT_FILE}" == "maxiwall.lua" ]; then
-      nano -c "${MAXIWALL_LUA}"
+      nano -c "${CODE_PATH}/${MAXIWALL_LUA}"
     elif [ "${EDIT_FILE}" == "eve.json" ]; then
       nano -c "${SURICATA_EVE_JSON}"
     elif [ "${EDIT_FILE}" == "fast.log" ]; then
@@ -2119,10 +2335,49 @@ while [ "$#" -gt 0 ]; do
     exit 0
     break
     ;;
-  d | bip | deny | block | block-ip | deny-ip)
-    IP="$2"
-    IP_COUNTRY="Unknown"
-    IP_LABEL="Unknown"
+  lbip | linode-bip | linode-deny | linode-block | linode-block-ip | linode-deny-ip)
+    SHORT_OPTS="v,d,l:"
+    LONG_OPTS="verbose,debug,firewall-label:"
+    OPTIONS=$(getopt -o "${SHORT_OPTS}" --long "${LONG_OPTS}" -n "${SCRIPT_NAME}" -- "$@" 2>&1)
+    RETVAL=$?
+    if [ ${RETVAL} != 0 ]; then
+      echo "[${SCRIPT_NAME}]: $(msg red)Error, ${OPTIONS}$(msg end)"
+      exit 1
+    fi
+    eval set -- "${OPTIONS}"
+    VERBOSE=false
+    DEBUG=false
+    # Because only one firewall can be used for one device. So I assign this as default name if not supplied
+    FIREWALL_LABEL="maxiwall1"
+    while true; do
+      case "$1" in
+      -v | --verbose)
+        VERBOSE=true
+        shift
+        ;;
+      -d | --debug)
+        DEBUG=true
+        shift
+        ;;
+      -l | --firewall-label)
+        FIREWALL_LABEL="$2"
+        shift 2
+        ;;
+      --)
+        shift
+        break
+        ;;
+      -*)
+        echo "[${SCRIPT_NAME}]: Error, invalid option e.g: ${SCRIPT_NAME} ${ACTION}"
+        exit 1
+        ;;
+      *)
+        break
+        ;;
+      esac
+    done
+
+    linode_block_ip "$@"
 
     exit 0
     break
